/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import accessDAO.LibroDAO;
import controller.InitialData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LibroModel;

/**
 *
 * @author marco
 */
public class jpLibro extends javax.swing.JPanel {

    private InitialData datos = new InitialData();
    private ArrayList IdLibrosLista = null;
    private ArrayList IdAutorLista;

    /**
     * Creates new form jpLibro
     */
    public jpLibro() {
        initComponents();
        setListaLibros();
        setListaIdRecursos();
        setListaIdAutor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtLibro = new javax.swing.JTable();
        jcLibro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtAnio = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtResumen = new javax.swing.JTextArea();
        jcAutor = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 51, 153));
        setPreferredSize(new java.awt.Dimension(650, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtLibro.setBackground(new java.awt.Color(0, 51, 153));
        jtLibro.setForeground(new java.awt.Color(204, 255, 255));
        jtLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtLibro);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 650, 160));

        jcLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opcion" }));
        add(jcLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Autor:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("ID Libro:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Resumen:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Año Publicación:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        add(jtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 90, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 90, -1));

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 90, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("CRUD PARA LIBRO");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jtResumen.setColumns(20);
        jtResumen.setRows(5);
        jScrollPane2.setViewportView(jtResumen);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 480, 80));

        jcAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un Autor" }));
        add(jcAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        String resumen = this.jtResumen.getText();
        String anio = this.jtAnio.getText();
        String id = jcLibro.getSelectedItem().toString();
        String autor = jcAutor.getSelectedItem().toString();
        if (anio.equals("") || resumen.equals("") || id.equals("Escoja una opcion") || autor.equals("Escoja un Autor")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar las casillas Resumen y año,además escoger una opcion de ID libro y Autor");
        } else {
            int id_lib = Integer.parseInt(id);
            int lib_anio = Integer.parseInt(anio);
            int lib_aut = Integer.parseInt(autor);
            LibroModel libro = new LibroModel(id_lib, resumen, lib_anio, lib_aut);
            LibroDAO libroDAO = new LibroDAO();
            libroDAO.insertLibro(libro);
        }
        setListaLibros();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        String resumen = this.jtResumen.getText();
        String anio = this.jtAnio.getText();
        String id = jcLibro.getSelectedItem().toString();
        String autor = jcAutor.getSelectedItem().toString();
        if (anio.equals("") || resumen.equals("") || id.equals("Escoja una opcion") || autor.equals("Escoja un Autor")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar las casillas Resumen y año,además escoger una opcion de ID libro y Autor");
        }else {
            int id_lib = Integer.parseInt(id);
            int lib_anio = Integer.parseInt(anio);
            int lib_aut = Integer.parseInt(autor);
            
            LibroModel libro = new LibroModel(id_lib, resumen, lib_anio, lib_aut);
            
            LibroDAO libroDAO = new LibroDAO();
            libroDAO.updateLibro(libro);
        }
        setListaLibros();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        String id = jcLibro.getSelectedItem().toString();
        if ( id.equals("Escoja una opcion") ) {
            JOptionPane.showMessageDialog(null, "Es escoger una opcion de ID libro");
        }else{
        int id_lib = Integer.parseInt((id));

            LibroDAO libroDAO = new LibroDAO();
            libroDAO.deleteLibro(id_lib);
        }
        setListaLibros();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JComboBox<String> jcAutor;
    private javax.swing.JComboBox<String> jcLibro;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTable jtLibro;
    private javax.swing.JTextArea jtResumen;
    // End of variables declaration//GEN-END:variables
String[] headers = {"ID", "Titulo", "Año", "Autor"};

    public void setListaLibros() {
        ArrayList<LibroModel> libros = datos.getLibrosLista();
        this.jtLibro.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jtLibro.setModel(tableModel);
        for (int i = 0; i < libros.size(); i++) {
            tableModel.addRow(libros.get(i).toArray());
        }
        this.jtLibro.setModel(tableModel);
    }

    public void setListaIdRecursos() {
        this.IdLibrosLista = new ArrayList(datos.getIdRecursoLista());
        for (Object object : IdLibrosLista) {
            jcLibro.addItem(object.toString() + "");
        }
    }

    public void setListaIdAutor() {
        this.IdAutorLista = new ArrayList(datos.getIdAutorLista());
        for (Object object : IdAutorLista) {
            jcAutor.addItem(object.toString() + "");
        }
    }
}
