/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import accessDAO.PrestamoDAO;
import controller.InitialData;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PrestamoModel;

/**
 *
 * @author marco
 */
public class jpPrestamo extends javax.swing.JPanel {

    private InitialData datos = new InitialData();
    private ArrayList IdLibrosLista;
    private ArrayList IdUsuariosLista;

    /**
     * Creates new form jpPrestamo
     */
    public jpPrestamo() {
        initComponents();
        setListaPrestamos();
        setListaIdRecursos();
        setListaIdUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrestamo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtIdPrestamo = new javax.swing.JTextField();
        jcIdUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcIdRecurso = new javax.swing.JComboBox<>();
        jdFechaPre = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtPrestamo.setBackground(new java.awt.Color(0, 102, 102));
        jtPrestamo.setForeground(new java.awt.Color(153, 255, 204));
        jtPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPrestamo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 550, 200));

        jLabel1.setForeground(new java.awt.Color(153, 255, 204));
        jLabel1.setText("ID Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        add(jtIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1));

        jcIdUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un Usuario" }));
        add(jcIdUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1));

        jLabel2.setForeground(new java.awt.Color(153, 255, 204));
        jLabel2.setText("ID Prestamo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 255, 204));
        jLabel3.setText("Fecha y Hora");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jcIdRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un Recurso" }));
        add(jcIdRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1));

        jdFechaPre.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        add(jdFechaPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        jLabel4.setForeground(new java.awt.Color(153, 255, 204));
        jLabel4.setText("ID Recurso");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 90, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, -1));

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        String pre_id = this.jtIdPrestamo.getText();
        String pre_usu = this.jcIdUsuarios.getSelectedItem().toString();
        String pre_rec = this.jcIdRecurso.getSelectedItem().toString();
        if (pre_id.equals("") || pre_usu.equals("Escoja un Usuario") || pre_rec.equals("Escoja un Recurso")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar Todas las casillas para poder agregar el Prestamo");
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String fecha = formato.format(jdFechaPre.getDate());
            int id = Integer.parseInt(pre_id);
            int rec = Integer.parseInt(pre_rec);
            PrestamoModel prestamo = new PrestamoModel(id, pre_usu, rec, fecha);
            PrestamoDAO prestamoDAO = new PrestamoDAO();
            prestamoDAO.insertPrestamo(prestamo);
        }
        setListaPrestamos();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        String pre_id = this.jtIdPrestamo.getText();
        String pre_usu = this.jcIdUsuarios.getSelectedItem().toString();
        String pre_rec = this.jcIdRecurso.getSelectedItem().toString();
        if (pre_id.equals("") || pre_usu.equals("Escoja un Usuario") || pre_rec.equals("Escoja un Recurso")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar Todas las casillas para poder actualizar el Prestamo");
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String fecha = formato.format(jdFechaPre.getDate());
            int id = Integer.parseInt(pre_id);
            int rec = Integer.parseInt(pre_rec);
            PrestamoModel prestamo = new PrestamoModel(id, pre_usu, rec, fecha);
            PrestamoDAO prestamoDAO = new PrestamoDAO();
            prestamoDAO.updatePrestamo(prestamo);
        }
        setListaPrestamos();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        String pre_id = this.jtIdPrestamo.getText();
        if (pre_id.equals("")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar la casilla Id para eliminar el Prestamo");
        } else {
            int id = Integer.parseInt(pre_id);
            PrestamoDAO prestamoDAO = new PrestamoDAO();
            prestamoDAO.deletePrestamo(id);
        }
        setListaPrestamos();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JComboBox<String> jcIdRecurso;
    private javax.swing.JComboBox<String> jcIdUsuarios;
    private com.toedter.calendar.JDateChooser jdFechaPre;
    private javax.swing.JTextField jtIdPrestamo;
    private javax.swing.JTable jtPrestamo;
    // End of variables declaration//GEN-END:variables
String[] headers = {"ID", "Usuario", "Recurso", "Fecha"};

    public void setListaPrestamos() {
        ArrayList<PrestamoModel> prestamo = datos.getPrestamoLista();
        this.jtPrestamo.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jtPrestamo.setModel(tableModel);
        for (int i = 0; i < prestamo.size(); i++) {
            tableModel.addRow(prestamo.get(i).toArray());
        }
        this.jtPrestamo.setModel(tableModel);
    }

    public void setListaIdRecursos() {
        this.IdLibrosLista = new ArrayList(datos.getIdRecursoLista());
        for (Object object : IdLibrosLista) {
            jcIdRecurso.addItem(object.toString() + "");
        }
    }

    public void setListaIdUsuarios() {
        this.IdUsuariosLista = new ArrayList(datos.getIdUsuariosLista());
        for (Object object : IdUsuariosLista) {
            jcIdUsuarios.addItem(object.toString() + "");
        }
    }
}
