/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import accessDAO.RevistaDAO;
import controller.InitialData;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RecursoModel;
import model.RevistaModel;

/**
 *
 * @author marco
 */
public class jpRevista extends javax.swing.JPanel {

    private InitialData datos = new InitialData();
    JComboBox<RecursoModel> revLista;
    private ArrayList IdRecursosLista = null;

    /**
     * Creates new form jpRevista
     */
    public jpRevista() {
        initComponents();
        setListaRevista();
        setListaIdRecursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtRevista = new javax.swing.JTable();
        jcbIdRec = new javax.swing.JComboBox<>();
        jlId = new javax.swing.JLabel();
        jlSerie = new javax.swing.JLabel();
        jlVolumen = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jtVolumen = new javax.swing.JTextField();
        jtSerie = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtRevista.setBackground(new java.awt.Color(0, 153, 153));
        jtRevista.setForeground(new java.awt.Color(255, 255, 255));
        jtRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtRevista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 220));

        jcbIdRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opcion" }));
        jcbIdRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIdRecActionPerformed(evt);
            }
        });
        add(jcbIdRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jlId.setText("ID Revista:");
        add(jlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jlSerie.setText("Serie:");
        add(jlSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jlVolumen.setText("Volumen:");
        add(jlVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 80, -1));

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));
        add(jtVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, -1));
        add(jtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 40, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CRUD PARA LA TABLA REVISTA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jcbIdRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIdRecActionPerformed
        //no encontre que poner aqui, hice la carga desde el constructor
    }//GEN-LAST:event_jcbIdRecActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        String volumen = this.jtVolumen.getText();
        String serie = this.jtSerie.getText();
        String id = jcbIdRec.getSelectedItem().toString();
        if (serie.equals("") || volumen.equals("") || id.equals("Escoja una opcion")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar las casillas Volumen, Serie y escoger una opcion de ID");
        } else {
            int id_rev = Integer.parseInt(id);
            int rev_vol = Integer.parseInt(volumen);
            int rev_ser = Integer.parseInt(serie);

            RevistaModel revista = new RevistaModel(id_rev, rev_vol, rev_ser);

            RevistaDAO revistaDAO = new RevistaDAO();
            revistaDAO.insertRevista(revista);

        }
        setListaRevista();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        String volumen = this.jtVolumen.getText();
        String serie = this.jtSerie.getText();
        String id = jcbIdRec.getSelectedItem().toString();
        if (serie.equals("") || volumen.equals("") || id.equals("Escoja una opcion")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar las casillas Volumen, Serie y escoger una opcion de ID");
        } else {
            int id_rev = Integer.parseInt(id);
            int rev_vol = Integer.parseInt(volumen);
            int rev_ser = Integer.parseInt(serie);

            RevistaModel recurso = new RevistaModel(id_rev, rev_vol, rev_ser);

            RevistaDAO revistaDAO = new RevistaDAO();
            revistaDAO.updateRevista(recurso);
        }
        setListaRevista();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        String volumen = this.jtVolumen.getText();
        String serie = this.jtSerie.getText();
        String id = jcbIdRec.getSelectedItem().toString();
        if (id.equals("Escoja una opcion")) {
            JOptionPane.showMessageDialog(null, "Es necesario escoger una opcion de ID");
        }
        else{
        int id_rev = Integer.parseInt((id));

            RevistaDAO revistaDAO = new RevistaDAO();
            revistaDAO.deleteRevista(id_rev);
        }
        setListaRevista();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JComboBox<String> jcbIdRec;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlSerie;
    private javax.swing.JLabel jlVolumen;
    private javax.swing.JTable jtRevista;
    private javax.swing.JTextField jtSerie;
    private javax.swing.JTextField jtVolumen;
    // End of variables declaration//GEN-END:variables
String[] headers = {"ID", "Volumen", "Serie"};

    public void setListaRevista() {
        ArrayList<RevistaModel> revista = datos.getRevistaLista();
        this.jtRevista.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jtRevista.setModel(tableModel);
        for (int i = 0; i < revista.size(); i++) {
            tableModel.addRow(revista.get(i).toArray());
        }
        this.jtRevista.setModel(tableModel);
    }

    public void setListaIdRecursos() {
        this.IdRecursosLista = new ArrayList(datos.getIdRecursoLista());
        for (Object object : IdRecursosLista) {
            jcbIdRec.addItem(object.toString() + "");
        }
    }
}
