/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import accessDAO.UsuariosDAO;
import controller.InitialData;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UsuariosModel;

/**
 *
 * @author marco
 */
public class jpUsuario extends javax.swing.JPanel {

    private InitialData datos = new InitialData();

    /**
     * Creates new form jpUsuario
     */
    public jpUsuario() {
        initComponents();
        setListaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jlApelllido = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jlApelllido1 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtCelular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtClave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsuario.setBackground(new java.awt.Color(102, 0, 102));
        jtUsuario.setForeground(new java.awt.Color(153, 255, 255));
        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jtUsuario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));
        add(jtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        jlApelllido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlApelllido.setForeground(new java.awt.Color(204, 255, 255));
        jlApelllido.setText("Apellido:");
        add(jlApelllido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, -1));

        jlApelllido1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlApelllido1.setForeground(new java.awt.Color(204, 255, 255));
        jlApelllido1.setText("Email:");
        add(jlApelllido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Celular:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        add(jtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Clave:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));
        add(jtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Fecha Nac:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, -1));

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jdFecha.setDateFormatString("yyyy-MM-dd");
        add(jdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("CRUD USUARIOS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        String id = this.jtUsername.getText();
        String nombre = this.jtNombre.getText();
        String apellido = this.jtApellido.getText();
        String email = this.jtEmail.getText();
        String celular = this.jtCelular.getText();
        String clave = this.jtClave.getText();

        if (id.equals("") || nombre.equals("") || apellido.equals("") || email.equals("") || celular.equals("") || clave.equals("")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar Todas las casillas para poder agregar el usuario");
            //System.out.println(fec.toString());

        } else {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = formato.format(jdFecha.getDate());
            Long cel = Long.parseLong(celular);
            UsuariosModel usuario = new UsuariosModel(id, nombre, apellido, email, cel, clave, fecha);
            UsuariosDAO usuarioDAO = new UsuariosDAO();
            usuarioDAO.insertUsuarios(usuario);
        }
        setListaUsuarios();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        String id = this.jtUsername.getText();
        String nombre = this.jtNombre.getText();
        String apellido = this.jtApellido.getText();
        String email = this.jtEmail.getText();
        String celular = this.jtCelular.getText();
        String clave = this.jtClave.getText();

        if (id.equals("") || nombre.equals("") || apellido.equals("") || email.equals("") || celular.equals("") || clave.equals("")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar Todas las casillas para poder agregar el usuario");
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = formato.format(jdFecha.getDate());
            Long cel = Long.parseLong(celular);
            UsuariosModel usuario = new UsuariosModel(id, nombre, apellido, email, cel, clave, fecha);
            UsuariosDAO usuarioDAO = new UsuariosDAO();
            usuarioDAO.updateUsuarios(usuario);
        }
        setListaUsuarios();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        String id = this.jtUsername.getText();

        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Es necesario llenar el campo ID para eliminar el usuario");
        } else {
            UsuariosDAO usuario = new UsuariosDAO();
            usuario.deleteUusarios(id);
        }
        setListaUsuarios();
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel jlApelllido;
    private javax.swing.JLabel jlApelllido1;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtClave;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtUsername;
    private javax.swing.JTable jtUsuario;
    // End of variables declaration//GEN-END:variables
String[] headers = {"ID", "Nombre", "Apellido", "Email", "Celular", "Clave", "Fecha Nac"};

    public void setListaUsuarios() {
        ArrayList<UsuariosModel> usuarios = datos.getUsuariosLista();
        this.jtUsuario.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jtUsuario.setModel(tableModel);
        for (int i = 0; i < usuarios.size(); i++) {
            tableModel.addRow(usuarios.get(i).toArray());
        }
        this.jtUsuario.setModel(tableModel);
    }
}
