
package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import view.jpUsuario;
import view.jpLibro;
import view.jpInicio;
/**
 *
 * @author marco
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpInicio inicio = new jpInicio();
        mostrarPanel(inicio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbInicio = new javax.swing.JButton();
        jbUsuario = new javax.swing.JButton();
        jbAutor = new javax.swing.JButton();
        jbLibro = new javax.swing.JButton();
        jbRevista = new javax.swing.JButton();
        jbPrestamo = new javax.swing.JButton();
        jbRecurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanelFondo.setBackground(new java.awt.Color(0, 102, 255));
        JPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 0, 66));

        jbInicio.setBackground(new java.awt.Color(0, 1, 66));
        jbInicio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home [#1393].png"))); // NOI18N
        jbInicio.setText("        INICIO     ");
        jbInicio.setBorder(null);
        jbInicio.setBorderPainted(false);
        jbInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInicioActionPerformed(evt);
            }
        });

        jbUsuario.setBackground(new java.awt.Color(0, 1, 66));
        jbUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profile [#1335].png"))); // NOI18N
        jbUsuario.setText(" USUARIO  ");
        jbUsuario.setBorder(null);
        jbUsuario.setBorderPainted(false);
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        jbAutor.setBackground(new java.awt.Color(0, 1, 66));
        jbAutor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbAutor.setForeground(new java.awt.Color(255, 255, 255));
        jbAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/script [#1601].png"))); // NOI18N
        jbAutor.setText("     AUTOR   ");
        jbAutor.setBorder(null);
        jbAutor.setBorderPainted(false);
        jbAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAutorActionPerformed(evt);
            }
        });

        jbLibro.setBackground(new java.awt.Color(0, 1, 66));
        jbLibro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbLibro.setForeground(new java.awt.Color(255, 255, 255));
        jbLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book [#1206].png"))); // NOI18N
        jbLibro.setText("   LIBRO      ");
        jbLibro.setBorder(null);
        jbLibro.setBorderPainted(false);
        jbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLibroActionPerformed(evt);
            }
        });

        jbRevista.setBackground(new java.awt.Color(0, 1, 66));
        jbRevista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbRevista.setForeground(new java.awt.Color(255, 255, 255));
        jbRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book [#1209].png"))); // NOI18N
        jbRevista.setText("  REVISTA    ");
        jbRevista.setBorder(null);
        jbRevista.setBorderPainted(false);
        jbRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRevistaActionPerformed(evt);
            }
        });

        jbPrestamo.setBackground(new java.awt.Color(0, 1, 66));
        jbPrestamo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jbPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fileboard_checklist [#1595].png"))); // NOI18N
        jbPrestamo.setText("   PRESTAMO  ");
        jbPrestamo.setBorder(null);
        jbPrestamo.setBorderPainted(false);
        jbPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrestamoActionPerformed(evt);
            }
        });

        jbRecurso.setBackground(new java.awt.Color(0, 1, 66));
        jbRecurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbRecurso.setForeground(new java.awt.Color(255, 255, 255));
        jbRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_left [#1506].png"))); // NOI18N
        jbRecurso.setText("  RECURSO  ");
        jbRecurso.setBorder(null);
        jbRecurso.setBorderPainted(false);
        jbRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRecursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jbRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        JPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 160, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra central.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        JPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 650, 100));

        jpContenedor.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        JPanelFondo.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 650, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        jpUsuario usuario = new jpUsuario();
        mostrarPanel(usuario);
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void jbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLibroActionPerformed
      jpLibro libro = new jpLibro();
        mostrarPanel(libro);
    }//GEN-LAST:event_jbLibroActionPerformed

    private void jbInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInicioActionPerformed
       jpInicio inicio = new jpInicio();
        mostrarPanel(inicio);
    }//GEN-LAST:event_jbInicioActionPerformed

    private void jbAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAutorActionPerformed
        jpAutor autor = new jpAutor();
        mostrarPanel(autor);
    }//GEN-LAST:event_jbAutorActionPerformed

    private void jbRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRevistaActionPerformed
        jpRevista revista = new jpRevista();
        mostrarPanel(revista);
    }//GEN-LAST:event_jbRevistaActionPerformed

    private void jbRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRecursoActionPerformed
        jpRecurso recurso = new jpRecurso();
        mostrarPanel(recurso);
    }//GEN-LAST:event_jbRecursoActionPerformed

    private void jbPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrestamoActionPerformed
        jpPrestamo prestamo = new jpPrestamo();
        mostrarPanel(prestamo);
    }//GEN-LAST:event_jbPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAutor;
    private javax.swing.JButton jbInicio;
    private javax.swing.JButton jbLibro;
    private javax.swing.JButton jbPrestamo;
    private javax.swing.JButton jbRecurso;
    private javax.swing.JButton jbRevista;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JPanel jpContenedor;
    // End of variables declaration//GEN-END:variables
 private void mostrarPanel(JPanel panel) {
        panel.setSize(650, 380);
        panel.setLocation(0, 0);

        jpContenedor.removeAll();
        jpContenedor.add(panel, BorderLayout.CENTER);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    }
}
